DROP TABLE IF EXISTS TRANSACTION_ITEMS_CATEGORIES;
create table TRANSACTION_ITEMS_CATEGORIES(
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    CATEGORY_ID INTEGER NOT NULL
);

DELETE FROM TRANSACTION_ITEMS_CATEGORIES;
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('水', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('電池', 4);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('キッチンペーパー', 4);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('青汁', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('Suntoryu銀麦', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('おかき', 3);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('緑茶', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('ロキソニン', 34);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('ストロー', 4);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('紅茶', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('ふりかけ', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('フルグノーラ', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('歯ブラシ', 4);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('ムーニーマン', 4);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('具材の煮物', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('天ぷらそば', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('コーヒー', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('スイートポテト', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('雑誌', 9);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('ゴミ袋', 4);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('はさみ', 6);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('刻みねぎ', 2);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('文庫', 9);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('週刊誌', 9);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('絵本', 9);
insert into TRANSACTION_ITEMS_CATEGORIES (NAME, CATEGORY_ID) VALUES ('文具', 6);
